name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  MY_DEMO_WEBAPP: webappextra 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{github.workspace}}/webtest2/webtest2.csproj
    - name: Build
      run: dotnet build ${{github.workspace}}/webtest2/webtest2.csproj --no-restore
    - name: Test
      run: dotnet test ${{github.workspace}}/webtest2/webtest2.csproj --no-build --verbosity normal
    - name: publish
      run: dotnet publish ${{github.workspace}}/webtest2/webtest2.csproj -c Release -o dotnetcorewebapp
    - name: deploy to azure webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.MY_DEMO_WEBAPP }}
        publish-profile: ${{ secrets.AZURE_WEBAPP }}
        package: './dotnetcorewebapp'
